services:
  nginx:
    depends_on:
      - books
      - orders
      - warehouse
      - front-end
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80

  front-end:
    image: ghcr.io/mcmastercce/bvd-103-mcmasterful-books/mcmasterful-books-docker:main
    volumes:
      - ./adapter:/source/adapter
      
  books:
    depends_on:
      - mongo-books
      - rabbitmq
    image: node:20
    env-env_file:
      - .env
    volumes:
      - ./books:/app
      - ./node_modules:/app/node_modules
      - ./tsconfig.json:/app/tsconfig.json
      - ./documented_types.ts:/documented_types.ts
    command: npx -y tsx ./index.ts
    working_dir: /app

  orders:
    depends_on:
      - mongo-order
      - rabbitmq
    image: node:20
    env-env_file:
      - .env
    volumes:
      - ./orders:/app
      - ./node_modules:/app/node_modules
      - ./tsconfig.json:/app/tsconfig.json
      - ./documented_types.ts:/documented_types.ts
    command: npx -y tsx ./index.ts
    working_dir: /app
    
  warehouse:
    depends_on:
      - mongo-warehouse
      - rabbitmq
    image: node:20
    env-env_file:
      - .env
    volumes:
      - ./warehouse:/app
      - ./node_modules:/app/node_modules
      - ./tsconfig.json:/app/tsconfig.json
      - ./documented_types.ts:/documented_types.ts
    command: npx -y tsx ./index.ts
    working_dir: /app

  docs:
    image: node:20
    env-env_file:
      - .env
    volumes:
      - ./docs:/app
      - ./node_modules:/app/node_modules
      - ./tsconfig.json:/app/tsconfig.json
      - ./build/swagger.json:/app/swagger.json
    command: npx -y tsx ./index.ts
    working_dir: /app
    

  mongo-books:
    image: mongo:latest
  mongo-warehouse:
    image: mongo:latest
  mongo-order:
    image: mongo:latest

  rabbitmq:
    image: rabbitmq:3.13-management