version: "4.0"

services:
  dev:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    
  mongo-books:
    image: mongo:latest
  mongo-warehouse:
    image: mongo:latest
  mongo-order:
    image: mongo:latest
    
  rabbitmq:
    image: rabbitmq:3.13-management