name: McMasterful Books Backend CI

on: 
    push: 
    pull_request:

jobs:
    format_and_lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '20'           
            - run: npm install
            - run: npm run lint
    
    check_types:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '20'           
            - run: npm install
            - run: npm run check-types

    test-books:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '20'           
            - run: npm install
            - run: npm run test:ci --workspace=books

    test-orders:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '20'           
            - run: npm install
            - run: npm run test:ci --workspace=orders

    test-warehouse:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '20'           
            - run: npm install
            - run: npm run test:ci --workspace=warehouse

    generate-client:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '20'           
            - run: npm install
            - run: ./generate-openapi.sh
            - uses: actions/upload-artifact@v4
              with:
                name: client-sdk
                path: client/